### ISSUE TITLE
On Laravel axios object does not have CSRF TOKEN no Laravel passport token so aut errors accesing API URLS

### ISSUE THREAD

**Issue by acacha** [acacha/forms#9]
app.js:18417 GET http://localhost:8080/api/v1/management/users-migration/totalNumberOfUsers 401 (Unauthorized)

**Comment by w0rd-driven** [comment]
Could you please tag and publish the latest revision with this included? Since the latest publish stops at 0.1.7 I tried adding this github repo but ran into problems because .npmignore includes src/, which blocks npm from installing the directory. Alternatively, if I knew a way to inject these settings in through one of my custom components it would let me limp along until this is published.
